<?php

use PP\MainLayout;

MainLayout::$title = !empty(MainLayout::$title) ? MainLayout::$title : 'Create Prisma PHP App';
MainLayout::$description = !empty(MainLayout::$description) ? MainLayout::$description : 'Generated by create Prisma PHP App';

?>

<html lang="en">

<head>
    <!-- Dynamic Meta Tags -->
    <link rel="icon" href="/favicon.ico" type="image/x-icon" sizes="16x16" />
    <!-- Dynamic Header Scripts -->
    <link href="/css/styles.css" rel="stylesheet" /> 
    <script type="module" src="/js/main.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&amp;display=swap" rel="stylesheet"/>
</head>

<body pp-spa="true" style="opacity:0;pointer-events:none;user-select:none;transition:opacity .18s ease-out;">
    <?= MainLayout::$children; ?>
    <!-- Dynamic Footer Scripts -->
</body>

</html>